### ISSUE TITLE
Source of the PDO article?

### ISSUE THREAD

**Issue by mehov** [colshrapnel/phpdelusions.net#5]
Hello,

First and foremost, thanks for the great work!

Noticed [a thing](https://phpdelusions.net/pdo#count) [or](https://phpdelusions.net/pdo#like) [two](https://phpdelusions.net/pdo#in) that I'd improve while reading https://phpdelusions.net/pdo, but unlike https://phpdelusions.net/sql_injection I can't see it's source here. Is this intentional, or I should have been looking elsewhere?

Thank you!

**Comment by colshrapnel** [comment]
Hello @mehov!
I am really sorry but I somehow missed this issue. 
If you are still interested, I will add the source here.

**Comment by miftygusein** [comment]
Hi @colshrapnel! 

Thank you for getting back to me. Sadly I have no recollection of what this was about. It's my own fault – I probably should have been more specific with what I wanted to suggest. Sorry about that!

I only remember appreciating your work here :)
